---
title: "Graticule Technical Screening"
author: "Arnold Huang"
date: '`r format(Sys.time(), "%Y %b %d")`'
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), 
                                              sub(".Rmd", 
                                                  paste0("_",
                                                         format(Sys.time(), "%Y%m%d"),
                                                         ".html"),
                                                  basename(inputFile)) )) })
output:
    html_document:
        code_folding: hide
        toc: true
        toc_depth: 3
        toc_float: true
        fig_width: 7
        fig_height: 7
        theme: sandstone
        number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)

```



```{r step 1: read data, warning = FALSE}
encounter_table = read.csv("~/projects/graticule/encounter_table.csv")
patient_table = read.csv("~/projects/graticule/patient_table.csv")



#1. Compute median age at index date for the exposed cohort (including CI at 95% confidence level)
exposed_cohort = encounter_table[encounter_table$exposure == "True", ]
# nrow(exposed_cohort) # 58 members in exp cohort
exposed_cohort_bday = merge(exposed_cohort, patient_table, by = "patientid", all.x = TRUE) 
exposed_cohort_bday$birthdate = as.Date(exposed_cohort_bday$birthdate, "%Y-%m-%d")
exposed_cohort_bday$encounterdate = as.Date(exposed_cohort_bday$encounterdate, "%Y-%m-%d")
exposed_cohort_bday$deceaseddate = as.Date(exposed_cohort_bday$deceaseddate, "%Y-%m-%d")

exposed_cohort_bday$age_at_index = as.numeric(round((exposed_cohort_bday$encounterdate - exposed_cohort_bday$birthdate)/365.25, 1))
summary(exposed_cohort_bday$age_at_index)
median(exposed_cohort_bday$age_at_index)

# 95% CI for mean
xbar = mean(exposed_cohort_bday$age_at_index)
ci_level = 0.95
n = nrow(exposed_cohort_bday)
margin = qt(1 - (1-ci_level)/2, df = n) * sd(exposed_cohort_bday$age_at_index)/sqrt(n)
c(xbar - margin, xbar+ margin)


# 95% CI for median
# https://www.statology.org/confidence-interval-for-median/
#j and k
q = 0.5 # for median
j = round(n * q - qnorm(1 - (1-ci_level)/2) * sqrt(n * q * (1-q)))
k = round(n * q + qnorm(1 - (1-ci_level)/2) * sqrt(n * q * (1-q)))
#c(j, k) # 22th and 36th observation
exposed_cohort_bday$age_at_index[c(j,k)]



# Compute aggregate time at risk for the exposed cohort, in person-days
# for deceased patient, time at risk = deceased_date - index_date
# for non-deceased patient, time at risk = study_end_date - index_date
# or we can write it as time_at_risk = min(deceased_date, "2022-12-31") - index_date

exposed_cohort_bday$last_day_at_risk = pmin(exposed_cohort_bday$deceaseddate, as.Date("2022-12-31"), na.rm = TRUE)


total_time_at_risk = as.numeric(sum(exposed_cohort_bday$last_day_at_risk - exposed_cohort_bday$encounterdate))

total_time_at_risk


###

# provide pseudo-code to select a 1:1 unexposed cohort based on the method outlined above.
# * Exposed subjects are exact matched with unexposed subjects based on age, gender, and a healthcare encounter within the same week
# * Matching is performed without replacement
# * Exposed subjects may serve as unexposed matches during any week before the week of their exposure date

```



